Update ping

diff --git a/linux/lab-3/ping b/linux/lab-3/ping
--- a/linux/lab-3/ping
+++ b/linux/lab-3/ping
@@ -1,1 +1,21 @@
+#!/bin/bash
+
+# Loop through the IP range 192.168.1.1 to 192.168.1.254
+for i in {1..254}
+do
+    # Construct the full IP address
+    ip="192.168.1.$i"
+
+    echo "Pinging $ip"
+
+    # Ping the IP address with a timeout of 1 second and a count of 1 packet
+    ping -c 1 -W 1 $ip
+
+    # Check the exit status of the ping command
+    if [ $? -eq 0 ]; then
+        echo "Server $ip is up and running"
+    else
+        echo "Server $ip is unreachable"
+    fi
+done
 
